export const DATA = [
    { nome: 'João Silva', status: true, datacriacao: new Date('2024-01-10'), usuariocriacao: 'admin', dataalteracao: new Date('2024-03-05'), usuarioalteracao: 'joao.alter' },
    { nome: 'Maria Oliveira', status: false, datacriacao: new Date('2023-11-20'), usuariocriacao: 'admin', dataalteracao: new Date('2024-01-15'), usuarioalteracao: 'maria.alter' },
    { nome: 'Carlos Mendes', status: true, datacriacao: new Date('2024-02-12'), usuariocriacao: 'admin', dataalteracao: new Date('2024-03-10'), usuarioalteracao: 'carlos.alter' },
    { nome: 'Fernanda Lima', status: false, datacriacao: new Date('2023-10-05'), usuariocriacao: 'fernanda', dataalteracao: new Date('2024-01-22'), usuarioalteracao: 'admin' },
    { nome: 'Bruno Rocha', status: true, datacriacao: new Date('2024-03-01'), usuariocriacao: 'admin', dataalteracao: new Date('2024-03-15'), usuarioalteracao: 'bruno.alter' },
    { nome: 'Juliana Castro', status: true, datacriacao: new Date('2024-01-25'), usuariocriacao: 'admin', dataalteracao: new Date('2024-02-20'), usuarioalteracao: 'juliana.alter' },
    { nome: 'Lucas Pereira', status: true, datacriacao: new Date('2023-08-11'), usuariocriacao: 'lucas', dataalteracao: new Date('2023-09-05'), usuarioalteracao: 'lucas.alter' },
    { nome: 'Ana Costa', status: false, datacriacao: new Date('2023-12-03'), usuariocriacao: 'ana', dataalteracao: new Date('2024-02-10'), usuarioalteracao: 'admin' },
    { nome: 'Rodrigo Gomes', status: true, datacriacao: new Date('2023-06-18'), usuariocriacao: 'rodrigo', dataalteracao: new Date('2024-01-17'), usuarioalteracao: 'rodrigo.alter' },
    { nome: 'Paula Silva', status: false, datacriacao: new Date('2023-05-25'), usuariocriacao: 'paula', dataalteracao: new Date('2024-01-30'), usuarioalteracao: 'paula.alter' },
    { nome: 'Roberto Almeida', status: true, datacriacao: new Date('2023-04-09'), usuariocriacao: 'admin', dataalteracao: new Date('2023-07-10'), usuarioalteracao: 'roberto.alter' },
    { nome: 'Tatiane Santos', status: true, datacriacao: new Date('2024-03-05'), usuariocriacao: 'tatiane', dataalteracao: new Date('2024-03-20'), usuarioalteracao: 'tatiane.alter' },
    { nome: 'Marcos Dias', status: false, datacriacao: new Date('2024-01-22'), usuariocriacao: 'admin', dataalteracao: new Date('2024-02-15'), usuarioalteracao: 'marcos.alter' },
    { nome: 'Carla Rodrigues', status: true, datacriacao: new Date('2023-07-17'), usuariocriacao: 'carla', dataalteracao: new Date('2024-02-05'), usuarioalteracao: 'carla.alter' },
    { nome: 'Felipe Gomes', status: true, datacriacao: new Date('2024-01-02'), usuariocriacao: 'admin', dataalteracao: new Date('2024-02-12'), usuarioalteracao: 'felipe.alter' },
    { nome: 'Sérgio Lima', status: true, datacriacao: new Date('2023-09-19'), usuariocriacao: 'sergio', dataalteracao: new Date('2024-02-25'), usuarioalteracao: 'sergio.alter' },
    { nome: 'Beatriz Ferreira', status: false, datacriacao: new Date('2024-03-10'), usuariocriacao: 'beatriz', dataalteracao: new Date('2024-03-15'), usuarioalteracao: 'beatriz.alter' },
    { nome: 'Eduardo Rocha', status: true, datacriacao: new Date('2024-02-28'), usuariocriacao: 'eduardo', dataalteracao: new Date('2024-03-07'), usuarioalteracao: 'eduardo.alter' },
    { nome: 'Letícia Souza', status: false, datacriacao: new Date('2023-08-14'), usuariocriacao: 'leticia', dataalteracao: new Date('2024-01-10'), usuarioalteracao: 'leticia.alter' },
    { nome: 'Marcelo Santos', status: true, datacriacao: new Date('2023-11-30'), usuariocriacao: 'marcelo', dataalteracao: new Date('2024-01-02'), usuarioalteracao: 'marcelo.alter' },
    { nome: 'Vanessa Pereira', status: true, datacriacao: new Date('2023-10-12'), usuariocriacao: 'vanessa', dataalteracao: new Date('2024-02-20'), usuarioalteracao: 'vanessa.alter' },
    { nome: 'Fernando Silva', status: false, datacriacao: new Date('2024-02-18'), usuariocriacao: 'fernando', dataalteracao: new Date('2024-03-05'), usuarioalteracao: 'fernando.alter' },
    { nome: 'Michele Rocha', status: true, datacriacao: new Date('2024-01-14'), usuariocriacao: 'admin', dataalteracao: new Date('2024-02-01'), usuarioalteracao: 'michele.alter' },
    { nome: 'Andréa Almeida', status: false, datacriacao: new Date('2024-03-01'), usuariocriacao: 'andrea', dataalteracao: new Date('2024-03-10'), usuarioalteracao: 'andrea.alter' },
    { nome: 'Vinícius Lima', status: true, datacriacao: new Date('2024-02-20'), usuariocriacao: 'vinicius', dataalteracao: new Date('2024-03-05'), usuarioalteracao: 'vinicius.alter' },
    { nome: 'Rosana Costa', status: false, datacriacao: new Date('2023-09-07'), usuariocriacao: 'rosana', dataalteracao: new Date('2024-01-15'), usuarioalteracao: 'rosana.alter' },
    { nome: 'Gustavo Martins', status: true, datacriacao: new Date('2023-12-15'), usuariocriacao: 'gustavo', dataalteracao: new Date('2024-02-10'), usuarioalteracao: 'gustavo.alter' }
  ];
  